language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hiddenroadss/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hiddenroadss/docker-react npm run test